DEF_CMD(kJmp , 16, "jmp" , true, true)
DEF_CMD(kJa  , 17, "ja"  , true, l_arg > r_arg)
DEF_CMD(kJae , 18, "jae" , true, l_arg >= r_arg)
DEF_CMD(kJb  , 19, "jb"  , true, l_arg <  r_arg)
DEF_CMD(kJbe , 20, "jbe" , true, l_arg <= r_arg)
DEF_CMD(kJe  , 21, "je"  , true, l_arg == r_arg)
DEF_CMD(kJne , 22, "jne" , true, l_arg != r_arg)
